-- vim.keymap.set(map.mode, map.key, map.action, map.options)
vim.keymap.set("n", "<leader>qq", "<cmd>qall<CR>", { desc = "[q]uit neovim" })
vim.keymap.set("n", "<leader>qQ",  "<cmd>qall!<CR>", { desc = "[Q]uit neovim - discard unsaved" })
vim.keymap.set("t", "<esc>",  "<c-\\><c-n>", { desc = "Exit terminal mode" })
vim.keymap.set("n", "<leader>wv",  "<C-w>v", { desc = "Split window vertically" })
vim.keymap.set("n", "<leader>ws",  "<C-w>s", { desc = "Split window horizontally" })
vim.keymap.set("n", "<leader>wc",  "<C-w>q", { desc = "Close window" })
vim.keymap.set("n", "<leader>w=",  "<C-w>=", { desc = "Equalize window sizes" })
vim.keymap.set("n", "<leader><up>",  "<C-w><up>", { desc = "Move FOCUS to the UPPER WINDOW" })
vim.keymap.set("n", "<leader><down>",  "<C-w><down>", { desc = "Move FOCUS to the LOWER WINDOW" })
vim.keymap.set("n", "<leader><left>",  "<C-w><left>", { desc = "Move FOCUS to the LEFT WINDOW" })
vim.keymap.set("n", "<leader><right>",  "<C-w><right>", { desc = "Move FOCUS to the RIGHT WINDOW" })
vim.keymap.set("n", "<leader>ww",  "<C-w>r", { desc = "Rotate windows clockwise" })
vim.keymap.set("n", "<leader>wW",  "<C-w>R", { desc = "Rotate windows anticlockwise" })
vim.keymap.set("n", "<leader>w<up>",  "<C-w>K", { desc = "Move window to the TOP" })
vim.keymap.set("n", "<leader>w<down>",  "<C-w>J", { desc = "Move window to the BOTTOM" })
vim.keymap.set("n", "<leader>w<left>",  "<C-w>H", { desc = "Move window to the LEFT" })
vim.keymap.set("n", "<leader>w<right>",  "<C-w>L", { desc = "Move window to the RIGHT" })
vim.keymap.set("n", "<leader>bb",  "<cmd>Telescope buffers<CR>", { desc = "TOOD List relevant Buffers" })
vim.keymap.set("n", "<leader>bB",  "<cmd>Telescope buffers<CR>", { desc = "List all Buffers" })
vim.keymap.set("n", "<leader><BS>",  "<cmd>b#<CR>", { desc = "Alternate Buffer" })
vim.keymap.set("n", "<leader>bp",  "<cmd>bp<CR>", { desc = "Previous Buffer" })
vim.keymap.set("n", "<leader>bn",  "<cmd>bn<CR>", { desc = "Next Buffer" })
vim.keymap.set("n", "<leader>bN",
  function()
    local new_buff = vim.api.nvim_create_buf(
      { listed = true },
      { scratch = false }
    )
    local curr_win = vim.api.nvim_get_current_win()
    vim.api.nvim_win_set_buf(curr_win, new_buff)
  end,
  { desc = "Create [N]ew buffer" }
)
vim.keymap.set("n", "<leader>bk",
  function()
    local force_close = vim.bo.filetype == "terminal"
    local buff = vim.api.nvim_get_current_buf()
    local ok, _ = pcall(vim.cmd, "buffer #")
    if not ok then
      vim.cmd("enew")
    end
    vim.api.nvim_buf_delete(buff, { force = force_close })
  end,
  { desc = "Kill Buffer" }
)

vim.keymap.set("n", "<leader>bK", "<cmd>%bd<CR>", { desc = "Kill All Buffers" })
vim.keymap.set("n", "<leader><leader>", "<cmd>Telescope git_files<CR>", { desc = "find git files" })
vim.keymap.set("n", "<leader>d", "<cmd>Oil<CR>", { desc = "open [d]irectory listing (oil)" })
vim.keymap.set("n", "<leader>gg", "<cmd>Neogit<CR>", { desc = "open [g]it" })
vim.keymap.set("n", "<leader>ff", "<cmd>Telescope find_files<CR>", { desc = "Find [f]iles" })
vim.keymap.set("n", "<leader>fr", "<cmd>Telescope oldfiles<CR>", { desc = "Find [r]ecent files" })
vim.keymap.set("n", "<leader>pf", "<cmd>Telescope git_files<CR>", { desc = "Find [r]ecent files" })
vim.keymap.set("n", "/", "<cmd>Telescope current_buffer_fuzzy_find<CR>", { desc = "Find in buffer" })
vim.keymap.set("n", "<leader>sr", "<cmd>Telescope grep_string<CR>", { desc = "grep for [r]eferences to the string under cursor" })
vim.keymap.set("n", "<leader>ss", "<cmd>Telescope live_grep<CR>", { desc = "live grep in current dir" })
vim.keymap.set("n", "<leader>cf", "<cmd>Format<CR>", { desc = "[f]ormat buffer" })
vim.keymap.set("n", "<leader>cl", "<cmd>Telescope diagnostics<CR>", { desc = "[l]ist lsp diagnostics" })
vim.keymap.set("n", "<leader>cn", "<cmd>lua vim.diagnostic.goto_next()<CR>", { desc = "[n]ext diagnostic" })
vim.keymap.set("n", "<leader>cp", "<cmd>lua vim.diagnostic.goto_prev()<CR>", { desc = "[p]revious diagnostic" })
vim.keymap.set("n", "<leader>c<CR>", function() vim.lsp.buf.code_action() end, { desc = "code actions" })
vim.keymap.set("n", "<leader>cd", "<cmd>Telescope lsp_definitions<CR>", { desc = "goto [d]efinitions" })
vim.keymap.set("n", "<leader>cr", "<cmd>Telescope lsp_references<CR>", { desc = "goto [r]eferences" })
vim.keymap.set("i", "<C-h>", function() vim.lsp.buf.signature_help() end, { desc = "Show signature help" })
vim.keymap.set("n", "<C-down>", "<cmd>cnext<CR>", { desc = "next quickfix" })
vim.keymap.set("n", "<C-up>", "<cmd>cprevious<CR>", { desc = "previous quickfix" })
vim.keymap.set("n", "<leader>ot>", "<cmd>edit ~/notes/agenda/todo.org<CR>", { desc = "open [t]odo.org" })
vim.keymap.set("n", "G", "Gzz", { desc = "Center when scrolling to the end of file" })
vim.keymap.set("n", "J", "mzJ`z", { desc = "Keep cursor inplace when [J]oining below" })
vim.keymap.set("x", "p", "P", { desc = "Do not loose the yank when pasting over a selection" })
vim.keymap.set("n", "<Esc>", "<cmd>nohlsearch<CR>", { desc = "Clear highlights on search when pressing <Esc> in normal mode" })
vim.keymap.set("v", "<M-Up>", ":m '<-2<CR>gv=gv", { desc = "Shift selection UP" })
vim.keymap.set("v", "<M-Down>", ":m '>+1<CR>gv=gv'", { desc = "Shift selection DOWN" })
