import = ["/home/saucoide/.config/alacritty/alacritty-theme/themes/taerminal.toml"]

[font]
size = 11.0

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.bold_italic]
family = "JetBrainsMono Nerd Font"
style = "Bold Italic"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Italic"

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[font.offset]
x = 0
y = 0

[font.glyph_offset]
x = 0
y = 0

[scrolling]
history = 10000

[window]
decorations = "None"
title = "alacritty"

[window.class]
general = "alacritty"
instance = "alacritty"

[window.padding]
x = 6
y = 6
